spring.application.name=ecommercespring
#server.address=0.0.0.0
server.port=8095


spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_spring
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.suffix=.html
spring.thymeleaf.mode=HTML

spring.security.user.name=admin
spring.security.user.password=admin




# Dimensione massima del file (10 MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# autenticazione mail:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=miaazienda2@gmail.com
spring.mail.password=nwobykzlgnjupuse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


